### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Alex-experiments** [cm8908/ContrastCAD#1]
Hi!

Thanks for your paper, it is very interesting!

I was trying to run the repo, but it appears that some files are missing.
Indeed, in _trainer/trainerCL.py_ can be found the following imports:
```
from .base import BaseTrainer
from .cl_loss import *
from .scheduler import GradualWarmupScheduler
```

However, base.py, cl_loss.py and scheduler.py seems to be missing from the trainer folder. Could you provide them as well?

It would also be great if you could upload a requirements file as well to simplify the process of running this repo :)

Thanks a lot!

**Comment by cm8908** [comment]
Added some missing files for you. It shall work now.
